GoogleCloudPlatform/alloydb-java-connector

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Version.java
- pom.xml
- samples/pom.xml
- versions.txt
Reverts GoogleCloudPlatform/alloydb-java-connector#56
> chore: revert "chore: make first version 0.1.0"

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Version.java
See See https://github.com/googleapis/release-please/blob/e1b6a8936f23079f1f4ddf0c66a2aa85802e1a70/docs/java-releases.md?plain=1#L23.
> chore: fix annotations in Version.java

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Version.java
Reverts GoogleCloudPlatform/alloydb-java-connector#61
> chore: Revert "chore: fix annotations in Version.java"

- .github/renovate.json
> chore: update renovate.json to group dependencies

- .github/renovate.json
- alloydb-jdbc-connector/pom.xml
- pom.xml
> chore: update dependency and renovate config

- .github/workflows/codeql.yml
> chore: add codeql action for security scan

- alloydb-jdbc-connector/pom.xml
> chore: update bouncycastle dependency version

- .github/workflows/approve-readme.yaml
- .github/workflows/ci.yaml
- .github/workflows/samples.yaml
> chore: default workflow permissions to read-only

- .github/renovate.json
Group dependencies in Renovate for kokoro and github
> chore: group dependencies in renovate for kokoro and github

- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java
> chore: fix unit tests

- .github/renovate.json
> chore: group com.google.errorprone dependencies in renovate config

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java
- pom.xml
> chore: fix lint warnings

- .github/release-please.yml
- README.md
> chore: configure release-please to update released version in doc file

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
> chore: send public key instead of CSR

- .github/renovate.json
> chore: fix label in renovate config

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/SocketFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
> chore: create a connector configuration value object

- README.md
> docs: add documentation for Admin Service Endpoint feature

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
> chore: prefer public key in API requests

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AsyncRateLimiter.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AsyncRateLimiterTest.java
> chore: Add AsyncRateLimiter.

- .github/workflows/ci.yaml
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDBDirectPathDataSource.java
Update test covering Auto IAM Authn on direct path: refresh access token if not set.
Fixes #267
> chore: update test to refresh access token if not set

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AlloyDBAdminClientFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoCacheFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoRepository.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCache.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCacheFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InMemoryConnectionInfoRepo.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubConnectionInfoCacheFactory.java
> deps: update proto-google-cloud-alloydb to v1

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfo.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Refresher.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/PauseCondition.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java
> chore: Add Refresher class.

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoCacheFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCache.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCacheFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubConnectionInfoCacheFactory.java
> chore: Use ListeningScheduledExecutorService

- .github/workflows/ci.yaml
Disabling flakybot as Pub/Sub topic for it has been deleted causing step to fail.
> ci: disable flakybot

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoCacheFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoRepository.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCache.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCacheFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Refresher.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InMemoryConnectionInfoRepo.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubConnectionInfoCacheFactory.java
> chore: Update DefaultConnectionInfoCache to use the Refresher

- pom.xml
> chore: set project-wide config for CLIRR

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/CredentialsProviderFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
- pom.xml
> chore: add ConnectorConfig

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoCache.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/CredentialsProviderFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCache.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Refresher.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/SocketFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDbJdbcNamedConnectorDataSourceFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITNamedConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubConnectionInfoCache.java
- pom.xml
> feat: add support for configuring named connections

- .github/workflows/ci.yaml
This reverts commit cd87a638c85aefb63ccfc5d8d2275f8bc8d2f2fb.
> ci: re-enable flakybot

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConstantCredentialFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/CredentialFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultCredentialFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/FileCredentialFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ServiceAccountImpersonatingCredentialFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/SupplierCredentialFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConstantCredentialsFactoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/FileCredentialFactoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/SupplierCredentialFactoryTest.java
- alloydb-jdbc-connector/src/test/resources/sample-credentials.json
> chore: add credential factory classes and tests

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java
> feat: add reset to ConnectorRegistry

- .github/workflows/ci.yaml
- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InternalConnectorRegistryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ServiceAccountImpersonatingCredentialFactoryTest.java
Add unit tests for `ServiceAccountImpersonatingCredentialFactory` and `InternalConnectorRegistry` classes.
> chore: add unit tests

- .github/sync-repo-settings.yaml
- .github/workflows/ci.yaml
Adding names to build steps so that debugging actions is easier in the UI.
> ci: add build step names for readability

- .github/workflows/ci.yaml
- alloydb-jdbc-connector/pom.xml
> chore: fix scheduled tests

- .github/workflows/ci.yaml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InternalConnectorRegistryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ServiceAccountImpersonatingCredentialFactoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubCredentialFactory.java
> chore: Stub Google Auth Credentials for unit tests

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AuthType.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
Add new connection config property for Auto IAM AuthN
Related to issue #185
> chore: add connection config property for Auto IAM AuthN

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InternalConnectorRegistryTest.java
> chore: Validate instance URI and raise exception. Add new tests.

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionSocket.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDbJdbcAutoIAMAuthNDataSourceFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITAutoIAMAuthNTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
- docs/jdbc.md
- pom.xml
> feat: add support for Auto IAM AuthN

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AlloyDBAdminClientFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepositoryFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorConfigTest.java
- docs/jdbc.md
> feat: add option to specify quota project

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AlloyDBAdminClientFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfo.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoRepository.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionSocket.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCache.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCacheFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepositoryFactory.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/IpType.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDbJdbcPublicIpDataSourceFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITPublicIpTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InMemoryConnectionInfoRepo.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InternalConnectorRegistryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubConnectionInfoCacheFactory.java
- docs/jdbc.md
> feat: add support for public IP

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoRepositoryFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/FakeSslServer.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InternalConnectorRegistryTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/MockAlloyDBAdminGrpc.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubAlloyDBAdminClientFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubConnectionInfoRepositoryFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubCredentialFactory.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/TestKeys.java
> chore: Add unit tests for Connector, including required mocks and stubs.

- alloydb-jdbc-connector/pom.xml
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Refresher.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/TerminalException.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorTest.java
- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java
> feat: Background refresh stops on unrecoverable Admin API response

- alloydb-jdbc-connector/pom.xml
- pom.xml
> chore: Define dependencyManagement at top-level to centralize the deps version

- README.md
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionSocket.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java
- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Refresher.java
Add support for debug logging.
Fixes #462
> feat: add support for debug logging

- alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionSocket.java
> fix: validate PSC DNS name in server certificate

- alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java
This ensures the test doesn't leave any threads running, which otherwise causes the test suite to hang until the test runner times out.
> chore: close refresher on test completion
