GoogleCloudPlatform/alloydb-java-connector

pom.xml
This shouldn't have been merged as it's failing the build.
Reverts GoogleCloudPlatform/alloydb-java-connector#66
=> chore: revert google-cloud-shared-dependencies upgrade

.github/release-trigger.yml
This line is necessary for Java-based releases and needs to match the internal configuration.
=> chore: update release-trigger.yml

.github/workflows/scorecard.yml
=> chore: add scorecard security scan

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCache.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InMemoryConnectionInfoRepo.java
=> fix: re-use existing connection info during force refresh

alloydb-jdbc-connector/pom.xml, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java
Reverts GoogleCloudPlatform/alloydb-java-connector#215
We should continue to use pem CSR for `v1beta` endpoint. Planning to move to public key and `v1` endpoint soon.
=> Revert "chore: send public key instead of CSR"

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AlloyDBAdminClientFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java
=> feat: add support for configuring admin service endpoint

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfo.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java
Instead of extracting the CA cert from `CertificateChain` we should instead use the `CaCert` field of the response body and let the API handle the work of extracting it.
=> chore: use CaCert from resp body

.github/renovate.json, .github/sync-repo-settings.yaml, .github/workflows/ci.yaml, alloydb-jdbc-connector/pom.xml, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/nativeimage/AlloyDBFeature.java, alloydb-jdbc-connector/src/main/resources/META-INF/native-image/com.google.cloud.alloydb/alloydb-connector-parent/native-image.properties, pom.xml
Fixes #36
As discussed the GraalVM job will run on periodic (schedule) event as it takes from 7 to 10min to finish ([example](https://github.com/GoogleCloudPlatform/alloydb-java-connector/actions/runs/6711868339/job/18240203950?pr=228))
=> feat: add support for GraalVM build

.github/renovate.json, alloydb-jdbc-connector/pom.xml
Use `logback-classic` dependency instead of `slf4j-jdk14` because it is much easier to configure.
Cloud SQL Java Connector uses `logback-classic` (https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/1680).
Note: the last version that supports Java 8 is `1.3.11`.
=> chore: use logback-classic dependency

docs/configuration.md, docs/jdbc.md
Add documentation describing how to use the `ConnectorRegistry` and `ConnectorConfig`.
Part of #273 
Part of #287
=> docs: add docs for connector configuration

.github/workflows/ci.yaml
We should skip `pull_request` event for unit tests as this event does not have access to repo secrets.
=> chore: configure GitHub Actions for unit tests to skip pull_request

.github/workflows/ci.yaml
Currently Flakybot is not being run on the `units` and `windows` builds. This PR enables it to run on the given builds.
=> ci: add Flakybot to unit test builds

.github/workflows/ci.yaml
Flakybot requires default credentials to connect to Pub/Sub. So we are adding the Google Cloud Auth action back to the unit tests builds
=> ci: add google cloud auth to unit tests builds

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java, docs/configuration.md
=> feat: add shutdown() to ConnectorRegistry

.github/renovate.json
Fixes #342 
Test/release/github dependencies commits will have prefix `chore(deps)`.
These commits will be ignored by release-please during the CHANGELOG generation.
=> chore: skip dep commits during changelog generation

.github/renovate.json
No need to update kokoro (release tool) dependencies consistently. Other connectors are not doing it.
=> chore: stop updating kokoro deps

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AccessTokenSupplier.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultAccessTokenSupplier.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/DefaultAccessTokenSupplierTest.java
This PR introduces a new class and interface `AccessTokenSupplier` and `DefaultAccessTokenSupplier` along with extensive unit tests. 
This new class will be used by the Connector to get the access token necessary to perform the metadata exchange.
Related to issue #185
=> chore: add AccessTokenSupplier

alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/DefaultAccessTokenSupplierTest.java, pom.xml
* Update dependency `com.google.cloud:google-cloud-shared-dependencies` to `v3.21.0`
* Switch from the deprecated constructor `GoogleCredentials(AccessToken)` to the constructor `GoogleCredentials(Builder builder)`.
=> chore: Migrate deprecated GoogleCredentials constructor

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoCache.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCache.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Refresher.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/StubConnectionInfoCache.java
When a computer wakes from sleep after more than ~1 hour and a client tries to connect, the internal certificate cache will have an expired certificate. As a result, clients who tried to connect after sleep would see bad certificate errors which would resolve only once the remaining refresh duration expired (sleep time + remaining duration).
This commit adds code to check if the client certificate is expired and immediately triggers a blocking refresh if it is. This means that in the case where a cached certificate has expired, it will be discarded and a new one will be retrieved before continuing with the connection.
Fixes #386
=> fix: ensure cert refresh recovers from sleep

pom.xml
Added `com.google.guava:failureaccess` to `<dependencyManagement>` to use the newest version.
To fix this error:
```
Error:  Require upper bound dependencies error for com.google.guava:failureaccess:1.0.1 paths to dependency are:
Error:  +-com.google.cloud:alloydb-jdbc-connector:1.0.1-SNAPSHOT
Error:    +-com.google.api.grpc:proto-google-cloud-alloydb-v1alpha:0.26.0
Error:      +-com.google.guava:failureaccess:1.0.1
Error:  and
Error:  +-com.google.cloud:alloydb-jdbc-connector:1.0.1-SNAPSHOT
Error:    +-com.google.api.grpc:proto-google-cloud-alloydb-connectors-v1:0.15.0
Error:      +-com.google.guava:failureaccess:1.0.1
Error:  and
Error:  +-com.google.cloud:alloydb-jdbc-connector:1.0.1-SNAPSHOT
Error:    +-com.google.api.grpc:grpc-google-cloud-alloydb-v1alpha:0.26.0
Error: …
```
=> chore(deps): Update dependency com.google.cloud:google-cloud-shared-dependencies to v3.28.1

.envrc.example, .github/workflows/ci.yaml, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfo.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionSocket.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepository.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/IpType.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDbJdbcPscDataSourceFactory.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoCacheTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionInfoTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITPscTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/MockAlloyDBAdminGrpc.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefresherTest.java, pom.xml
AlloyDB will soon support PSC-based connections. This commit adds support for PSC in the Java Connector by exposing a new `alloydbIpType=PSC`. When the option is set, the Java Connector retrieves the PSC DNS name from the connection info response and then attempts to connect to that DNS name.
Presently, PSC requires some additional setup on the caller's part (e.g., creation of a Cloud DNS managed zone, with an A record pointing to the PSC service attachment). Those configuration details will be provided elsewhere and not here.
Fixes #445
=> feat: add support for PSC

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/AlloyDBAdminClientFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoRepositoryFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionSocket.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorRegistry.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoRepositoryFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITDefaultConnectionInfoRepositoryTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InternalConnectorRegistryTest.java
Add a new method to `addArtifactId()` to the public IP to allow external applications to add their names to the AlloyDB Admin API User-Agent header.
It matches the Cloud SQL Java Connector API - [code](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/core/src/main/java/com/google/cloud/sql/ConnectorRegistry.java#L66)
=> chore: add addArtifactId() to ConnectorRegistry

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConstantCredentialFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/CredentialFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultCredentialFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/FileCredentialFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ServiceAccountImpersonatingCredentialFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/SupplierCredentialFactory.java
The OAuth scopes should be set for the credentials.
When the scopes are missing, the following error is seeing (from https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2788):
```
Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: 400 Bad Request
POST https://oauth2.googleapis.com/token
***"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."***, iss: github-actions-ci@spring-cloud-gcp-ci.iam.gserviceaccount.com
at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:129)
at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:538)
at …
```
=> fix: Add scope for Credentials

.github/workflows/ci.yaml
Include missing configuration to run a workflow job on "tests: run" label for only external contributors.
For b/336892651
=> chore: Update ci.yaml

.github/sync-repo-settings.yaml
Don't require PRs to be up-to-date. Requiring this check is
only useful when there is a steady stream of feature work. 
Meanwhile, when merging dependencies updates, we have
to run the CI checks repeatedly for little value. So disable the
check for the branch to be up-to-date.
=> chore: Update sync-repo-settings.yaml

.github/renovate.json5
This commit groups all non-major and patch dependency updates together to reduce the noise from renovate.
=> chore: simplify renovate configuration

.github/workflows/ci.yaml
GitHub provides no reasonable and secure way to run integration tests against PRs from forks. This PR adjusts the CI builds to skip integration tests on PRs from forks and otherwise runs the entire test suite for internal PRs. In addition, integration tests will run on main regardless to catch any regressions.
=> chore: skip integration tests on forks

.github/workflows/ci.yaml, pom.xml
This change sets up to use a managed GraalVM test image.
See https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/2030.
Fixes #561.
=> ci: use graalvm-community and native image maven plugin

.github/renovate.json5
The GraalVM build broke when we updated the JUnit dependencies. Rather than disable upgrades, this PR splits out the dependencies as a separate rule to make it easier to catch problems in the future.
Related to https://github.com/GoogleCloudPlatform/alloydb-java-connector/issues/574
=> chore: manage JUnit deps separately

pom.xml
Restore older versions of JUnit platform components.
Tested by:
docker run -it -v $PWD:/code --rm ghcr.io/graalvm/graalvm-community:22 bash
And then running tests.
Fixes #574
=> chore: fix GraalVM nightly build

pom.xml
This resolves the error we're seeing in our nightly GraalVM builds:
TestEngine with ID 'junit-jupiter' failed to discover tests
It also pulls in the latest JUnit dependencies.
Fixes https://github.com/GoogleCloudPlatform/alloydb-java-connector/issues/585
=> chore: upgrade and specify all JUnit transitive dependencies

README.md
Debug logging doesn't need to include the entire application. Just the Connector will do. This commit updates the guidance to target just the Connector.
=> docs: improve debug logging guidance

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionConfig.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectorConfig.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/DefaultConnectionInfoCacheFactory.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/LazyConnectionInfoCache.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/RefreshAheadConnectionInfoCache.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/RefreshCalculator.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/RefreshStrategy.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDbJdbcConnectorDataSourceFactory.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDbJdbcNamedConnectorDataSourceFactory.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectionConfigTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorConfigTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ITConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/LazyConnectionInfoCacheTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/RefreshAheadConnectionInfoCacheTest.java, docs/configuration.md
By default the connector will continue to use a refresh ahead strategy, where client certificates are refreshed by a background thread. The lazy strategy by comparison is useful for when the Connector runs in serverless environments and background threads may not run reliably, e.g., when the CPU is throttled.
This commit adds the lazy refresh strategy and updates the configuration documentation to demonstrate how to use the feature.
Fixes #565
=> feat: add support for lazy refresh

.github/renovate.json5
JUnit is no longer a problem as we've addressed the underlying dependency issue in prior changes.
Error Prone core dropped support for JDK 11 in v2.32.0 [1]. So for now, update Error Prone core separately to make it easier to fix the issue without breaking our usual dependency updates.
[1]: https://github.com/google/error-prone/releases/tag/v2.31.0
=> chore: improve renovate config

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java
Without using daemon threads, the Connector will prevent a calling process from exiting cleanly.
Fixes #617
=> fix: use daemon threads internally

alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/ConnectorTest.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/TestCertificates.java
This commit updates the connector tests to run locally. The previous use of 127.0.0.2 does not work on non-Linux machines.
Also, this commit removes superfluous and duplicate tests that verify exception paths, speeding up the test suite at the same time.
=> chore: make connector tests run locally

alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/ConnectionInfoRepository.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/Connector.java, alloydb-jdbc-connector/src/main/java/com/google/cloud/alloydb/InternalConnectorRegistry.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InMemoryConnectionInfoRepo.java, alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/InternalConnectorRegistryTest.java
When the connector is closed, it must also close the underlying AlloyDB gRPC-based client to avoid any errors. This ensures a clean shutdown of the Connector generally.
=> fix: close AlloyDB gRPC client on connector close

.github/renovate.json5, .github/workflows/ci.yaml, pom.xml
This will ensure breaking dependency changes are caught sooner, at the
cost of slower builds. Once we better understand how GraalVM builds are
breaking (e.g., Junit deps changes), we can restore the build to nightly.
In addition, this commit downgrades Junit dependencies back to the last
working version and configures a Renovate group so we can address them
separately.
Fixes #627
=> chore: run GraalVM build regularly

.github/workflows/ci.yaml, .kokoro/dependencies.sh
This matches the official policy:
https://cloud.google.com/java/docs/supported-java-versions
=> chore: test Java 21

.github/renovate.json5
This change ensures all JUnit updates go together in a separate PR.
=> chore: group all junit jupiter packages together

.github/workflows/ci.yaml, .kokoro/build.sh, alloydb-jdbc-connector/src/main/resources/META-INF/native-image/com.google.cloud/alloydb-jdbc-connector/reflect-config.json, pom.xml
This commit cleans up additional leftovers following #645.
In particular:
- Rename the CI workflow from graalvm17 to just graalvm
- Remove unnecessary dependency management config and build config for the
GraalVM profile, and instead use the configuration from the parent POM.
- Remove unnecessary values from reflect config.
=> chore: simplify GraalVM config
